# Generated by Django 3.0.5 on 2020-04-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0002_slambook_my_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slambook',
            name='my_ideal',
        ),
    ]
