# Generated by Django 3.0.5 on 2020-04-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0003_remove_slambook_my_ideal'),
    ]

    operations = [
        migrations.AddField(
            model_name='slambook',
            name='my_goal',
            field=models.CharField(default='', max_length=250),
        ),
    ]
