# Generated by Django 3.0.5 on 2020-04-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0005_remove_slambook_my_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='slambook',
            name='my_profile',
            field=models.ImageField(blank=True, upload_to='slam_images/'),
        ),
    ]
