# Generated by Django 3.0.5 on 2020-04-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0006_slambook_my_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slambook',
            name='my_profile',
            field=models.ImageField(blank=True, null=True, upload_to='slam_images/'),
        ),
    ]
