# Generated by Django 3.0.5 on 2020-11-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0008_slambook_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slambook',
            name='my_favourite_festival',
        ),
        migrations.RemoveField(
            model_name='slambook',
            name='my_favourite_webiste',
        ),
    ]
