# Generated by Django 3.0.5 on 2020-12-08 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Friends', '0010_auto_20201208_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slambook',
            name='user',
        ),
        migrations.AddField(
            model_name='slambook',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
